import type { RecognitionTitle } from './types'

function title(id: string, label: string, classLock: RecognitionTitle['classLock'], rarity: RecognitionTitle['rarity']): RecognitionTitle {
  return { id, label, classLock, rarity }
}

export const HOMEROOM_TITLES: RecognitionTitle[] = [
  title('hr-morning-mvp', 'Morning MVP', 'homeroom', 'uncommon'),
  title('hr-class-champion', 'Class Champion', 'homeroom', 'rare'),
  title('hr-reagan-royalty', 'Reagan Room Royalty', 'homeroom', 'legendary'),
  title('hr-routine-rockstar', 'Routine Rockstar', 'homeroom', 'common'),
  title('hr-leadership-legend', 'Leadership Legend', 'homeroom', 'rare'),
  title('hr-homeroom-hero', 'Homeroom Hero', 'homeroom', 'uncommon'),
  title('hr-ready-position', 'Ready Position Royalty', 'homeroom', 'uncommon'),
  title('hr-line-leader', 'Line Leader Legend', 'homeroom', 'common'),
  title('hr-morning-meeting', 'Morning Meeting MVP', 'homeroom', 'uncommon'),
  title('hr-snacktime', 'Snacktime Superstar', 'homeroom', 'common'),
  title('hr-class-captain', 'Classroom Captain', 'homeroom', 'uncommon'),
  title('hr-kindness', 'Kindness Champion', 'homeroom', 'uncommon'),
  title('hr-responsibility', 'Responsibility Royalty', 'homeroom', 'rare'),
  title('hr-focus-force', 'Focus Force Leader', 'homeroom', 'uncommon'),
  title('hr-teamwork', 'Teamwork Titan', 'homeroom', 'uncommon'),
  title('hr-transition', 'Transition Pro', 'homeroom', 'common'),
  title('hr-hallway', 'Hallway Hero', 'homeroom', 'common'),
  title('hr-dismissal', 'Dismissal Dynamo', 'homeroom', 'uncommon'),
  title('hr-cleanup', 'Clean-Up Captain', 'homeroom', 'common'),
  title('hr-materials', 'Materials Master', 'homeroom', 'common'),
  title('hr-table-team', 'Table Team Titan', 'homeroom', 'uncommon'),
  title('hr-voice-level', 'Voice Level Victor', 'homeroom', 'common'),
  title('hr-ranger', 'Reagan Room Ranger', 'homeroom', 'rare'),
  title('hr-culture', 'Class Culture Champion', 'homeroom', 'rare'),
  title('hr-routine-defender', 'Daily Routine Defender', 'homeroom', 'uncommon'),
  title('hr-calm-coach', 'Calm Coach', 'homeroom', 'uncommon'),
  title('hr-respect', 'Respect Rockstar', 'homeroom', 'common'),
  title('hr-super-starter', 'Super Starter', 'homeroom', 'common'),
  title('hr-all-day', 'All-Day Ace', 'homeroom', 'rare'),
  title('hr-citizenship', 'Citizenship Champion', 'homeroom', 'uncommon'),
]

export const READING_TITLES: RecognitionTitle[] = [
  title('rd-word-wizard', 'Word Wizard', 'reading', 'uncommon'),
  title('rd-fluency', 'Fluency Hero', 'reading', 'common'),
  title('rd-vocabulary', 'Vocabulary Victor', 'reading', 'uncommon'),
  title('rd-story-sleuth', 'Story Sleuth', 'reading', 'uncommon'),
  title('rd-rockstar', 'Reading Rockstar', 'reading', 'rare'),
  title('rd-page-turner', 'Page Turner', 'reading', 'common'),
  title('rd-evidence', 'Text Evidence Expert', 'reading', 'uncommon'),
  title('rd-comprehension', 'Comprehension Captain', 'reading', 'uncommon'),
  title('rd-main-idea', 'Main Idea Master', 'reading', 'uncommon'),
  title('rd-inference', 'Inference Investigator', 'reading', 'rare'),
  title('rd-context', 'Context Clue Champion', 'reading', 'uncommon'),
  title('rd-genre', 'Genre Genius', 'reading', 'uncommon'),
  title('rd-chapter', 'Chapter Champion', 'reading', 'common'),
  title('rd-book-boss', 'Book Boss', 'reading', 'rare'),
  title('rd-literacy', 'Literacy Legend', 'reading', 'legendary'),
  title('rd-phonics', 'Phonics Phenom', 'reading', 'uncommon'),
  title('rd-expression', 'Expression Expert', 'reading', 'common'),
  title('rd-summary', 'Summary Specialist', 'reading', 'uncommon'),
  title('rd-purpose', "Author's Purpose Ace", 'reading', 'uncommon'),
  title('rd-character', 'Character Detective', 'reading', 'uncommon'),
  title('rd-plot', 'Plot Pathfinder', 'reading', 'uncommon'),
  title('rd-theme', 'Theme Tracker', 'reading', 'uncommon'),
  title('rd-word-attack', 'Word Attack Warrior', 'reading', 'rare'),
  title('rd-sentence', 'Sentence Sleuth', 'reading', 'common'),
  title('rd-routine', 'Reading Routine Rockstar', 'reading', 'common'),
  title('rd-spelling', 'Spelling Star', 'reading', 'common'),
  title('rd-voyager', 'Vocabulary Voyager', 'reading', 'uncommon'),
  title('rd-paragraph', 'Paragraph Pro', 'reading', 'common'),
  title('rd-discussion', 'Discussion Leader', 'reading', 'uncommon'),
  title('rd-close-reading', 'Close Reading Champion', 'reading', 'rare'),
]

export const MATH_TITLES: RecognitionTitle[] = [
  title('math-ninja', 'Number Ninja', 'math', 'uncommon'),
  title('math-problem', 'Problem-Solving Pro', 'math', 'uncommon'),
  title('math-fraction', 'Fraction Hero', 'math', 'common'),
  title('math-equation', 'Equation Explorer', 'math', 'uncommon'),
  title('math-master', 'Math Master', 'math', 'rare'),
  title('math-computation', 'Computation Captain', 'math', 'common'),
  title('math-place-value', 'Place Value Pro', 'math', 'common'),
  title('math-multiplication', 'Multiplication Master', 'math', 'uncommon'),
  title('math-division', 'Division Dynamo', 'math', 'uncommon'),
  title('math-data', 'Data Detective', 'math', 'uncommon'),
  title('math-geometry', 'Geometry Guru', 'math', 'uncommon'),
  title('math-measurement', 'Measurement Master', 'math', 'common'),
  title('math-strategy', 'Strategy Star', 'math', 'uncommon'),
  title('math-logic', 'Logic Legend', 'math', 'rare'),
  title('math-mission', 'Math Mission Leader', 'math', 'uncommon'),
  title('math-area', 'Area Ace', 'math', 'common'),
  title('math-perimeter', 'Perimeter Pro', 'math', 'common'),
  title('math-decimal', 'Decimal Detective', 'math', 'uncommon'),
  title('math-fact-flash', 'Math Fact Flash', 'math', 'common'),
  title('math-array', 'Array Ace', 'math', 'common'),
  title('math-pattern', 'Pattern Pathfinder', 'math', 'uncommon'),
  title('math-reasoning', 'Reasoning Rockstar', 'math', 'uncommon'),
  title('math-number-sense', 'Number Sense Navigator', 'math', 'uncommon'),
  title('math-word-problem', 'Word Problem Warrior', 'math', 'uncommon'),
  title('math-talk', 'Math Talk MVP', 'math', 'rare'),
  title('math-precision', 'Precision Pro', 'math', 'common'),
  title('math-graphing', 'Graphing Genius', 'math', 'uncommon'),
  title('math-estimation', 'Estimation Expert', 'math', 'common'),
  title('math-fraction-fan', 'Fraction Fanatic', 'math', 'uncommon'),
  title('math-equation-eng', 'Equation Engineer', 'math', 'rare'),
]

export const SHARED_TITLES: RecognitionTitle[] = [
  title('shared-high-flier', 'High Flier', 'shared', 'uncommon'),
  title('shared-super-scholar', 'Super Scholar', 'shared', 'uncommon'),
  title('shared-focus', 'Focus Champion', 'shared', 'common'),
  title('shared-effort', 'Effort Expert', 'shared', 'common'),
  title('shared-team', 'Team Player', 'shared', 'common'),
  title('shared-kindness', 'Kindness Leader', 'shared', 'common'),
  title('shared-participation', 'Participation Pro', 'shared', 'common'),
  title('shared-on-task', 'On-Task Ace', 'shared', 'common'),
  title('shared-respect', 'Respect Leader', 'shared', 'common'),
  title('shared-star', 'Classroom Star', 'shared', 'uncommon'),
  title('shared-challenge', 'Challenge Champion', 'shared', 'uncommon'),
  title('shared-growth', 'Growth Mindset Hero', 'shared', 'uncommon'),
  title('shared-perseverance', 'Perseverance Pro', 'shared', 'common'),
  title('shared-positive', 'Positive Leader', 'shared', 'common'),
  title('shared-quiet', 'Quiet Champion', 'shared', 'common'),
  title('shared-helper', 'Helper Hero', 'shared', 'common'),
  title('shared-listener', 'Super Listener', 'shared', 'common'),
  title('shared-ready', 'Ready to Learn Leader', 'shared', 'common'),
  title('shared-attitude', 'Awesome Attitude', 'shared', 'common'),
  title('shared-all-star', 'All-Star Student', 'shared', 'rare'),
]

export const DEFAULT_TITLE_BANK: RecognitionTitle[] = [
  ...HOMEROOM_TITLES,
  ...READING_TITLES,
  ...MATH_TITLES,
  ...SHARED_TITLES,
]
