import type { BoardDeck } from './types'

/**
 * DB-1 seed data — a simple two-page classroom board.
 * All text is generic and student-safe. No real names, accounts, or secrets.
 */
export function createSeedBoard(): BoardDeck {
  return {
    id: 'board-morning',
    title: 'Morning Board',
    activePageId: 'page-morning',
    createdAt: 0,
    updatedAt: 0,
    pages: [
      {
        id: 'page-morning',
        title: 'Morning Board',
        background: { type: 'gradient', from: '#0f172a', to: '#1e3a8a', angleDeg: 135 },
        teacherNotes: 'Sample teacher note — never projected to present mode.',
        objects: [
          {
            id: 'text-heading',
            kind: 'text',
            x: 160,
            y: 120,
            w: 1600,
            h: 220,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 1,
            config: {
              kind: 'text',
              text: 'Good Morning',
              fontSize: 140,
              color: '#f8fafc',
              align: 'center',
            },
          },
          {
            id: 'text-directions',
            kind: 'text',
            x: 160,
            y: 400,
            w: 1600,
            h: 140,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 1,
            config: {
              kind: 'text',
              text: 'Read the morning message, then begin your work quietly.',
              fontSize: 56,
              color: '#e2e8f0',
              align: 'center',
            },
          },
          {
            id: 'clock-top',
            kind: 'clock',
            x: 1560,
            y: 96,
            w: 280,
            h: 150,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: { kind: 'clock', format: '12h', label: '8:00' },
          },
          {
            id: 'timer-top',
            kind: 'timer',
            x: 80,
            y: 96,
            w: 280,
            h: 150,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: { kind: 'timer', durationMinutes: 10, label: '10:00' },
          },
          {
            id: 'spotify-bottom',
            kind: 'spotifyNowPlayingPlaceholder',
            x: 1320,
            y: 880,
            w: 520,
            h: 130,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: { kind: 'spotifyNowPlayingPlaceholder', label: 'Now Playing' },
          },
          {
            id: 'link-bottom',
            kind: 'link',
            x: 80,
            y: 880,
            w: 520,
            h: 130,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: {
              kind: 'link',
              url: 'https://example.com',
              label: 'Class Website',
            },
          },
        ],
      },
      {
        id: 'page-work',
        title: 'Morning Work',
        background: { type: 'gradient', from: '#111827', to: '#334155', angleDeg: 135 },
        objects: [
          {
            id: 'text-heading-2',
            kind: 'text',
            x: 160,
            y: 120,
            w: 1600,
            h: 200,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 1,
            config: {
              kind: 'text',
              text: 'Morning Work',
              fontSize: 120,
              color: '#f8fafc',
              align: 'center',
            },
          },
          {
            id: 'text-directions-2',
            kind: 'text',
            x: 160,
            y: 380,
            w: 1600,
            h: 120,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 1,
            config: {
              kind: 'text',
              text: 'Complete page 1 in your journal.',
              fontSize: 52,
              color: '#e2e8f0',
              align: 'center',
            },
          },
          {
            id: 'video-center',
            kind: 'videoEmbed',
            x: 560,
            y: 560,
            w: 800,
            h: 380,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: { kind: 'videoEmbed', src: 'https://example.com', label: 'Video' },
          },
          {
            id: 'timer-top-2',
            kind: 'timer',
            x: 1560,
            y: 96,
            w: 280,
            h: 150,
            rotation: 0,
            locked: false,
            visible: true,
            layer: 2,
            config: { kind: 'timer', durationMinutes: 15, label: '15:00' },
          },
        ],
      },
    ],
  }
}
